apiVersion: v2
name: cassanova
description: Web UI for Apache Cassandra management
type: application
version: 1.0.1
appVersion: "1.11.0"
keywords:
  - cassandra
  - database
  - management
  - monitoring
  - k8ssandra
home: https://github.com/PoorTuna/Cassanova
sources:
  - https://github.com/PoorTuna/Cassanova
maintainers:
  - name: Oren Kessler
