{{- if and .Values.config.k8s.kubeconfig (not .Values.config.k8s.kubeconfigSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cassanova.fullname" . }}-kubeconfig
  labels:
    {{- include "cassanova.labels" . | nindent 4 }}
type: Opaque
stringData:
  kubeconfig: |
    {{- .Values.config.k8s.kubeconfig | nindent 4 }}
{{- end }}
